services:
  db:
    image: mysql/mysql-server
    ports:
      - 3306:3306
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
  python:
    build:
      context: .
    links:
      - db:db
    volumes:
      - ./:/usr/src/finances
