services:
  db:
    image: mysql/mysql-server:8.0
    ports:
      - 3306:3306
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=foobar
      - MYSQL_DATABASE=finances
      - MYSQL_USER=bernie
      - MYSQL_PASSWORD=berniepw
  python:
    build:
      context: .
    command: sleep infinity
    volumes:
      - ./:/usr/src/finances:ro
