services:
  db:
    image: mysql/mysql-server:8.0
    ports:
      - 3306:3306
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    environment:
      - MYSQL_ROOT_PASSWORD=foobar
      - MYSQL_DATABASE=my_database
  python:
    build:
      context: .
    command: sleep infinity
    links:
      - db:db
    volumes:
      - ./:/usr/src/finances:ro
